CREATE DATABASE IF NOT EXISTS web_terminal;
USE web_terminal;

CREATE TABLE IF NOT EXISTS todos (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  title       VARCHAR(255) NOT NULL,
  description TEXT,
  category    VARCHAR(100) DEFAULT NULL,
  priority    ENUM('low','medium','high') DEFAULT 'medium',
  status      ENUM('pending','in_progress','completed','learned') NOT NULL DEFAULT 'pending',
  due_date    DATE DEFAULT NULL,
  completed   BOOLEAN DEFAULT FALSE,
  position    INT DEFAULT 0,
  parent_id   INT DEFAULT NULL,
  recurring   VARCHAR(50) DEFAULT NULL,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (parent_id) REFERENCES todos(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS tags (
  id    INT AUTO_INCREMENT PRIMARY KEY,
  name  VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS todo_tags (
  todo_id INT NOT NULL,
  tag_id  INT NOT NULL,
  PRIMARY KEY (todo_id, tag_id),
  FOREIGN KEY (todo_id) REFERENCES todos(id) ON DELETE CASCADE,
  FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS time_logs (
  id         INT AUTO_INCREMENT PRIMARY KEY,
  todo_id    INT NOT NULL,
  start_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  end_time   TIMESTAMP NULL DEFAULT NULL,
  duration   INT DEFAULT NULL,
  FOREIGN KEY (todo_id) REFERENCES todos(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS shared_links (
  id         INT AUTO_INCREMENT PRIMARY KEY,
  token      VARCHAR(64) UNIQUE NOT NULL,
  todo_ids   TEXT NOT NULL,
  password   VARCHAR(255) DEFAULT NULL,
  expires_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
